### ISSUE TITLE
Lets check the laplacians

### ISSUE THREAD

**Issue by ktavabi** [ilabsbrainteam/face-to-face-connectivity#1]
Hi Dan. This is what I am doing to arrive at the Graph Laplacian as per Ginset (personal communications included)

```
# compute ROI level envelope power
        print(" Envcorr ...", end="")
        aec = envelope_correlation(label_ts)
        assert aec.shape == (len(rois), len(rois))
        # compute Nx laplacian as per:
        # Ginestet, C. E., Li, J., Balachandran, P., Rosenberg, S., &
        # Kolaczyk, E. D. (2017). Hypothesis testing for network data
        # in functional neuroimaging. Annals of Applied Statistics,
        # 11(2), 725–750. https://doi.org/10.1214/16-AOAS1015
        _, laplacian[si, ix] = csgraph.laplacian(aec, return_diag=True) 
```
FYI `aec` is a `Epochs` iterator.  
First we should figure out if `csgraph.laplacians` returns the same as what you've done with `networkx` [here](https://github.com/ilabsbrainteam/face-to-face-connectivity/blob/06ed73fbe3b8942008ac35a0b01999fd3fd30524/analysis/make-xarrays.py#L109
). If that's in agreement then we're on the same page regarding the `shortest path` measure.

Beyond that I am not sure what all else is going on in your scripts. The challenge for me is figuring out how to effectively reduce data dimensionality in a data driven or reasonable _a priori_ manner. I am using [this](https://www.nature.com/articles/s41593-020-00726-z) as a guideline.

**Comment by drammock** [comment]
```py
from networkx.linalg.laplacianmatrix import laplacian_matrix
from scipy.sparse.csgraph import laplacian

nx_laplacian = laplacian_matrix(graph)
scipy_laplacian = laplacian(nx.to_scipy_sparse_matrix(graph))
np.testing.assert_array_almost_equal(scipy_laplacian.toarray(), nx_laplacian.toarray(), decimal=14)
```

They're equivalent to 14 decimals, assertion fails if I change to `decimal=15`.  It looks like in your code you're only keeping the degrees, not the whole matrix?  The docs say that the second element returned by `csgraph.laplacian` is just the diagonal (aka the node degrees).

> Beyond that I am not sure what all else is going on in your scripts.

`graph-level-stats.py` basically follows the Ginestet paper:

- `get_halfvec()` is their φ function first introduced in Theorem 3
- I skip calculating Sigma-hat directly because you only need Sigma inverse to get the t-value, and the R package `corpcor` (written by Schäfer and Strimmer, authors of the 2005 paper cited by Ginestet) has a function that calculates sigma-hat inverse directly/efficiently.
- I'm computing a one-sample test statistic `t_observed` as in their Corollary 2 (because I'm comparing within-subject, condition1 laplacian minus condition2 laplacian)
- degrees of freedom and p-value are also as described in Corollary 2
- the `lambda_hat` code follows their definition in the first paragraph of section 4.4
- the rest of the script after that is output / plotting

The loop is run once for the whole graph and once for the subgraph comprising the ROI edges (defined [here](https://github.com/ilabsbrainteam/face-to-face-connectivity/blob/main/params/roi-edges.yaml), based on Corbetta & Schulman 2002 for attention nodes, and on Hickok & Poeppel's dual-stream model for speech perception nodes).  The ROI labels are in turn defined [here](https://github.com/ilabsbrainteam/face-to-face-connectivity/blob/06ed73fbe3b8942008ac35a0b01999fd3fd30524/params/rois.yaml#L24) as collections of APARC_sub labels.  That's my approach to dimensionality reduction in a nutshell; it ends up with 74 labels total / 17 ROI labels (though the real number is the number of edges in each graph).  I haven't read the Bijsterbosch et al paper before, I'll take a look.

**Comment by drammock** [comment]
(I should add that restricting to a subgraph of ROI nodes/edges is legit according to Ginestet Theorem 3)

**Comment by ktavabi** [comment]
> (I should add that restricting to a subgraph of ROI nodes/edges is legit according to Ginestet Theorem 3)

That was my next instinct to point that out.
My use case is also within-subjects and I did my comparisons directly on node results using...

```
from hotelling.stats import hotelling_t2 as t2
out = t2(y[['nabla_rest', 'nabla_task']])
```
So I'd like to look at your script a bit more and see if I can reproduce my results. Thanks for sharing, this is a boost in confidence. 

Side note: I see you're playing with `xarray` i/o; I had already landed on these same results using the same module but at the time `xarray` was wondering off Eric's reservation 😅 This time around I've managed to wrangle everything just with PANDAS. I should also add that my thinking all along has been to use `hotelling.stats` because ultimately I think people at ILABS will land on doing connectivity analysis in time on smaller ROI constellations; that way we or most likely you 😒 will hook into @larsoner implementation of Hotelling in MNEFUN. Reopen, if you have thoughts to add. I'll open new issue if I have questions about your script(s).

And again sorry for being a sociopath lately.

**Comment by drammock** [comment]
just a couple final thoughts:

1. if you're doing a within-subjs comparison, hotelling's T^2 is over-conservative by a factor of 2... that's why I did the 1-sample test: in Ginestet's theorem 3, treating one condition as L-hat and the other as Lambda (the "reference" condition); or equivalently, treating the difference between conditions as L-hat, and Lambda as all zeros.
2. re: xarray, I did that mostly because the new `mne_connectivity` module uses xarray under the hood, so if I'm going to port this implementation to mne_connectivity (as I hope to do eventually) I figured I might as well teach myself how xarray works first :)  Put another way, I think I could have done what I did with just numpy and some careful mental record-keeping; xarray is optional (as you've already discovered, since you're doing it with just pandas)

feel free to open new issues if more questions come up.
